"""Dataset provenance: machine-readable manifest + content-version hashing.

The dataset in this repository is SYNTHETIC, generated by
`scripts/generate_data.py` (seeded, reproducible). The manifest exists so
every model version, experiment run and monitoring report can state exactly
which data it was built from — and so nobody mistakes it for a real
production extract.

`dataset_version` is a content hash of the raw tables (sorted by filename,
then file bytes) truncated to 12 hex chars. Any change to the generator or
its seed produces a new version; identical inputs always produce the same
version, which is what makes experiments comparable across runs.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime

import pandas as pd

from supplychainxai import config

SCHEMA_VERSION = "1.1.0"  # bump when raw table schemas change
GENERATOR = "scripts/generate_data.py"


def _hash_file(path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def compute_dataset_version(raw_dir=None) -> str:
    """Stable content hash across all raw CSVs (order-independent)."""
    raw_dir = raw_dir or config.DATA_RAW
    files = sorted(raw_dir.glob("*.csv"), key=lambda p: p.name)
    combined = hashlib.sha256()
    for f in files:
        combined.update(f.name.encode())
        combined.update(_hash_file(f).encode())
    return combined.hexdigest()[:12]


def build_manifest(
    raw: dict[str, pd.DataFrame] | None = None, processed: dict[str, pd.DataFrame] | None = None
) -> dict:
    """Describe the dataset honestly: origin, shape, coverage, schema.

    `raw` / `processed` accept preloaded frames (pipeline mode); when omitted
    the manifest describes whatever is currently on disk.
    """
    version = compute_dataset_version()

    def _describe(df: pd.DataFrame) -> dict:
        info: dict = {"rows": len(df)}
        if "date" in df.columns and len(df):
            dates = pd.to_datetime(df["date"], errors="coerce").dropna()
            if len(dates):
                info["date_min"] = str(dates.min().date())
                info["date_max"] = str(dates.max().date())
        return info

    raw_info = {name: _describe(df) for name, df in (raw or {}).items()}
    if not raw_info:
        raw_info = {
            p.stem: {"rows": sum(1 for _ in open(p)) - 1}
            for p in sorted(config.DATA_RAW.glob("*.csv"))
        }

    if processed and "sales" in processed:
        sales = processed["sales"]
    else:
        sales = pd.read_csv(config.PROCESSED_FILES["sales"])
    n_skus = int(sales["sku"].nunique()) if len(sales) else 0
    n_suppliers = 0
    sup_path = config.RAW_FILES["suppliers"]
    if sup_path.exists():
        n_suppliers = int(pd.read_csv(sup_path).shape[0])

    manifest = {
        "dataset_name": "supplychainxai_synthetic_ops",
        "dataset_version": version,
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "source_type": "synthetic_generated",
        "provenance_statement": (
            "This repository uses synthetic/generated supply-chain data designed "
            "to reproduce realistic procurement, demand, supplier, inventory and "
            "pricing patterns. It is NOT real-world production data; costs and "
            "savings derived from it are simulated. Generated by "
            f"{GENERATOR} with a fixed seed (fully reproducible)."
        ),
        "generator": GENERATOR,
        "schema_version": SCHEMA_VERSION,
        "tables": raw_info,
        "n_skus": n_skus,
        "n_suppliers": n_suppliers,
        "files": {p.name: _hash_file(p)[:12] for p in sorted(config.DATA_RAW.glob("*.csv"))},
    }
    return manifest


def write_manifest(manifest: dict | None = None) -> dict:
    manifest = manifest or build_manifest()
    out = config.DATA_METADATA / "dataset_manifest.json"
    out.write_text(json.dumps(manifest, indent=2))
    return manifest


def load_manifest() -> dict:
    path = config.DATA_METADATA / "dataset_manifest.json"
    if path.exists():
        return json.loads(path.read_text())
    return write_manifest()
